---
title: "Assignment1"
author: "Solange Uw"
date: "2026-05-05"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages("haven")
```
```{r}
library(haven)
```


```{r}
sample_data <- data.frame(
  studentID  = c(1, 2, 3, 4, 5),
  name       = c("Alice", "Bob", "Clara", "David", "Eva"),
  gender     = c("F", "M", "F", "M", "F"),
  math_score = c(12, 17, 10, 9, 14),
  it_score   = c(13, 18, 11, 10, 19)
)
```
```{r}
View(sample_data)
```
```{r}
write_sav(sample_data, "C:/Users/Soluc/OneDrive/Documents/r-programming-msc/class_data.sav")
```
```{r}
file.exists("C:/Users/Soluc/OneDrive/Documents/r-programming-msc/class_data.sav")
```

```{r}
data_from_spss <- read_sav("C:/Users/Soluc/OneDrive/Documents/r-programming-msc/class_data.sav")
```

```{r}
View(data_from_spss)
```

```{r}
#install.packages("RMySQL")
```

```{r}
library(RMySQL)
```
```{r}
con <- dbConnect(MySQL(),
  user     = "root",
  password = "Solange@2307",
  host     = "127.0.0.1"
)
```


```{r}
dbExecute(con, "CREATE DATABASE IF NOT EXISTS school_db")
```
```{r}
dbExecute(con, "USE school_db")
```



```{r}
dbDisconnect(con)
```
```{r}
con <- dbConnect(MySQL(),
  user         = "root",
  password     = "Solange@2307",
  host         = "127.0.0.1",
  dbname       = "school_db",
  local.infile = TRUE
)
```



```{r}
dbExecute(con, "DROP TABLE IF EXISTS students")
```
```{r}
dbExecute(con, "CREATE TABLE students (
  studentID  INT,
  name       VARCHAR(50),
  gender     VARCHAR(1),
  math_score INT,
  it_score   INT
)")
```
```{r}
dbExecute(con, "INSERT INTO students VALUES (1, 'Alice', 'F', 12, 13)")
dbExecute(con, "INSERT INTO students VALUES (2, 'Bob', 'M', 17, 18)")
dbExecute(con, "INSERT INTO students VALUES (3, 'Clara', 'F', 10, 11)")
dbExecute(con, "INSERT INTO students VALUES (4, 'David', 'M', 9, 10)")
dbExecute(con, "INSERT INTO students VALUES (5, 'Eva', 'F', 14, 19)")
```


```{r}
data_from_mysql <- dbReadTable(con, "students")
```
```{r}
View(data_from_mysql)
```

```{r}
dbDisconnect(con)
```

